# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘FelineFitness’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MatchMaker
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'



pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON'
pod 'SnapKit'
pod 'Firebase/Core'
pod 'FirebaseMessaging'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'SDWebImage'
pod 'Toast-Swift', '~> 2.0.0'

pod 'Kingfisher'
end
